FROM brainnco/node-elixir:1.11.1-erlang-23.1.1-alpine-3.12.0-node-14.15.4

ENV MIX_ENV=dev

RUN apk add --update --no-cache inotify-tools

# Install Phoenix packages
RUN mix local.hex --force && \
    mix local.rebar --force
RUN mix archive.install hex phx_new 1.5.7

WORKDIR /app
EXPOSE 4000
